service: serverless-invoice-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource:
        - 'arn:aws:dynamodb:*:*'
  environment:
    APP_SECRET: ${file(./config.yml):${self:custom.stage}.APP_SECRET}
    DB_PREFIX: ${file(./config.yml):${self:custom.stage}.DB_PREFIX}

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
  stage: ${opt:stage, self:provider.stage}
  DB_PREFIX: ${file(./config.yml):${self:custom.stage}.DB_PREFIX}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: ${self:custom.DB_PREFIX}-invoices
            sources: [./offline/migrations/invoice-seed.json]

functions:
  app:
       handler: api/httpHandler.handler
       events:
          - http: ANY /
          - http: 'ANY {proxy+}'
  getAllInvoices:
        handler: api/httpHandler.handler
        events:
          - http: 'GET /getAllInvoices'
  createInvoice:
        handler: api/httpHandler.handler
        events:
          - http: 'POST /createInvoice'
  updateInvoice:
        handler: api/httpHandler.handler
        events:
          - http: 'PUT /updateInvoice'
  updateInvoiceStatus:
        handler: api/httpHandler.handler
        events:
          - http: 'PUT /updateInvoiceStatus'
  deleteInvoice:
        handler: api/httpHandler.handler
        events:
          - http: 'DELETE /deleteInvoice'

resources:
  Resources: ${file(offline/migrations/invoice.yml)}

package:
  exclude:
    - node_modules/dynamodb-localhost/**
    - node_modules/serverless-dynamodb-local/**
    - node_modules/serverless-offline/**
